services:
  router:
    build:
      context: ./router
      dockerfile: dockerfile
    container_name: router
    cap_add:
      - NET_ADMIN
    networks:
      - subnet1
      - subnet2

  host1:
    build:
      context: ./host1
      dockerfile: dockerfile
    container_name: host1
    cap_add:
      - NET_ADMIN
    networks:
      - subnet1

  host2:
    build:
      context: ./host2
      dockerfile: dockerfile
    container_name: host2
    cap_add:
      - NET_ADMIN
    networks:
      - subnet2

networks:
  subnet1:
    driver: bridge
  subnet2:
    driver: bridge
